package com.ishangke.edunav.manager.converter;

import java.util.ArrayList;
import java.util.List;

import com.ishangke.edunav.common.constant.Constant;
import com.ishangke.edunav.common.utilities.DateUtility;
import com.ishangke.edunav.commoncontract.model.ClassPhotoBo;
import com.ishangke.edunav.commoncontract.model.CourseBo;
import com.ishangke.edunav.commoncontract.model.TeacherBo;
import com.ishangke.edunav.dataaccess.model.ClassPhotoEntityExt;
import com.ishangke.edunav.dataaccess.model.CourseEntityExt;
import com.ishangke.edunav.dataaccess.model.TeacherEntityExt;

public class CourseConverter {
    public static CourseBo toBo(CourseEntityExt e) {
        CourseBo courseBo = new CourseBo();
        courseBo.setAddress(e.getAddress());
        courseBo.setAddressId(e.getAddressId());
        courseBo.setAddressLat(e.getAddressLat());
        courseBo.setAddressLng(e.getAddressLng());
        courseBo.setAssignments(e.getAssignments());
        courseBo.setBonusService(e.getBonusService());
        courseBo.setBookingTotal(e.getBookingTotal());
        courseBo.setBookingType(e.getBookingType());
        courseBo.setCashback(e.getCashback());
        courseBo.setCashbackDate(e.getCashbackDate() == null ? Constant.DEFAULTNULL : e.getCashbackDate().getTimeInMillis());
        courseBo.setCashbackDateStart(e.getCashbackDateStart() == null ? Constant.DEFAULTNULL : e.getCashbackDateStart().getTimeInMillis());
        courseBo.setCashbackDateEnd(e.getCashbackDateEnd() == null ? Constant.DEFAULTNULL : e.getCashbackDateEnd().getTimeInMillis());
        courseBo.setCashbackEnd(e.getCashbackEnd());
        courseBo.setCashbackStart(e.getCashbackStart());
        courseBo.setCategoryId(e.getCategoryId());
        courseBo.setCategoryIdSet(e.getCategoryIdSet());
        courseBo.setCategoryName(e.getCategoryName());
        courseBo.setCategoryRank(e.getCategoryRank());
        courseBo.setCategoryValue(e.getCategoryValue());
        courseBo.setCertification(e.getCertification());
        courseBo.setCircleId(e.getCircleId());
        courseBo.setCircleIdSet(e.getCircleIdSet());
        courseBo.setCircleName(e.getCircleName());
        courseBo.setCircleValue(e.getCircleValue());
        if (e.getClassPhotoList() != null) {
            List<ClassPhotoBo> list = new ArrayList<>();
            for (ClassPhotoEntityExt a : e.getClassPhotoList()) {
                list.add(ClassPhotoConverter.toBo(a));
            }
            courseBo.setClassPhotoList(list);
        }
        courseBo.setClassSize(e.getClassSize());
        courseBo.setClassTeacher(e.getClassTeacher());
        courseBo.setClassType(e.getClassType());
        courseBo.setClassTypeSet(e.getClassTypeSet());
        courseBo.setCommission(e.getCommission());
        courseBo.setContact(e.getContact());
        courseBo.setCourseHourLength(e.getCourseHourLength());
        courseBo.setCourseHourNum(e.getCourseHourNum());
        courseBo.setCourseHourNumEnd(e.getCourseHourNumEnd());
        courseBo.setCourseHourNumSet(e.getCourseHourNumSet());
        courseBo.setCourseHourNumStart(e.getCourseHourNumStart());
        courseBo.setCourseIntro(e.getCourseIntro());
        courseBo.setCourseName(e.getCourseName());
        courseBo.setCourseTemplateId(e.getCourseTemplateId());
        courseBo.setCourseTemplateIdSet(e.getCourseTemplateIdSet());
        courseBo.setCreateTime(e.getCreateTime() == null ? Constant.DEFAULTNULL : e.getCreateTime().getTimeInMillis());
        courseBo.setCreateTimeEnd(e.getCreateTimeEnd() == null ? Constant.DEFAULTNULL : e.getCreateTimeEnd().getTimeInMillis());
        courseBo.setCreateTimeStart(e.getCreateTimeStart() == null ? Constant.DEFAULTNULL : e.getCreateTimeStart().getTimeInMillis());
        courseBo.setCutoffDate(e.getCutoffDate() == null ? Constant.DEFAULTNULL : e.getCutoffDate().getTimeInMillis());
        courseBo.setCutoffDateEnd(e.getCutoffDateEnd() == null ? Constant.DEFAULTNULL : e.getCutoffDateEnd().getTimeInMillis());
        courseBo.setCutoffDateStart(e.getCutoffDateStart() == null ? Constant.DEFAULTNULL : e.getCutoffDateStart().getTimeInMillis());
        courseBo.setDiscount(e.getDiscount());
        courseBo.setDiscountEnd(e.getDiscountEnd());
        courseBo.setDiscountStart(e.getDiscountStart());
        courseBo.setDownloadMaterials(e.getDownloadMaterials());
        courseBo.setEnabled(e.getEnabled());
        courseBo.setExtracurricular(e.getExtracurricular());
        courseBo.setFinishDate(e.getFinishDate() == null ? Constant.DEFAULTNULL : e.getFinishDate().getTimeInMillis());
        courseBo.setFinishDateEnd(e.getFinishDateEnd() == null ? Constant.DEFAULTNULL : e.getFinishDateEnd().getTimeInMillis());
        courseBo.setFinishDateStart(e.getFinishDateStart() == null ? Constant.DEFAULTNULL : e.getFinishDateStart().getTimeInMillis());
        courseBo.setFinishTime1(e.getFinishTime1());
        courseBo.setFinishTime2(e.getFinishTime2());
        courseBo.setGoal(e.getGoal());
        courseBo.setHighScoreReward(e.getHighScoreReward());
        courseBo.setId(e.getId());
        courseBo.setIdSet(e.getIdSet());
        courseBo.setInstName(e.getInstName());
        courseBo.setLastModifyTime(e.getLastModifyTime() == null ? Constant.DEFAULTNULL : e.getLastModifyTime().getTimeInMillis());
        courseBo.setLastModifyTimeEnd(e.getLastModifyTimeEnd() == null ? Constant.DEFAULTNULL : e.getLastModifyTimeEnd().getTimeInMillis());
        courseBo.setLastModifyTimeStart(e.getLastModifyTimeStart() == null ? Constant.DEFAULTNULL : e.getLastModifyTimeStart().getTimeInMillis());
        courseBo.setLocationId(e.getLocationId());
        courseBo.setLocationIdSet(e.getLocationIdSet());
        courseBo.setLocationName(e.getLocationName());
        courseBo.setLocationValue(e.getLocationValue());
        courseBo.setLogoUrl(e.getLogoUrl());
        courseBo.setMarking(e.getMarking());
        courseBo.setNoRefundDate(e.getNoRefundDate() == null ? Constant.DEFAULTNULL : e.getNoRefundDate().getTimeInMillis());
        courseBo.setNoRefundDateStart(e.getNoRefundDateStart() == null ? Constant.DEFAULTNULL : e.getNoRefundDateStart().getTimeInMillis());
        courseBo.setNoRefundDateEnd(e.getNoRefundDateEnd() == null ? Constant.DEFAULTNULL : e.getNoRefundDateEnd().getTimeInMillis());
        courseBo.setOpenCourseRequirement(e.getOpenCourseRequirement());
        courseBo.setOriginalPrice(e.getOriginalPrice());
        courseBo.setOriginalPriceEnd(e.getOriginalPriceEnd());
        courseBo.setOriginalPriceStart(e.getOriginalPriceStart());
        courseBo.setOutline(e.getOutline());
        courseBo.setPartnerDistinction(e.getPartnerDistinction());
        courseBo.setPartnerId(e.getPartnerId());
        courseBo.setPartnerIdSet(e.getPartnerIdSet());
        courseBo.setPartnerIntro(e.getPartnerIntro());
        courseBo.setPartnerQualification(e.getPartnerQualification());
        courseBo.setPartnerRating(e.getPartnerRating());
        courseBo.setPassAgreement(e.getPassAgreement());
        courseBo.setPopularity(e.getPopularity());
        courseBo.setPopularityEnd(e.getPopularityEnd());
        courseBo.setPopularitySet(e.getPopularitySet());
        courseBo.setPopularityStart(e.getPopularityStart());
        courseBo.setQualityAssurance(e.getQualityAssurance());
        courseBo.setQuestionBank(e.getQuestionBank());
        courseBo.setQuestionSession(e.getQuestionSession());
        courseBo.setQuiz(e.getQuiz());
        courseBo.setRating(e.getRating());
        courseBo.setReference(e.getReference());
        courseBo.setRegLocation(e.getRegLocation());
        courseBo.setRegPhone(e.getRegPhone());
        courseBo.setSchooltimeDay(e.getSchooltimeDay());
        courseBo.setSchooltimeDaySet(e.getSchooltimeDaySet());
        courseBo.setSchooltimeWeek(e.getSchooltimeWeek());
        courseBo.setSchooltimeWeekSet(e.getSchooltimeWeekSet());
        courseBo.setServiceCharge(e.getServiceCharge());
        courseBo.setStartDate(e.getStartDate() == null ? Constant.DEFAULTNULL : e.getStartDate().getTimeInMillis());
        courseBo.setStartDateEnd(e.getStartDateEnd() == null ? Constant.DEFAULTNULL : e.getStartDateEnd().getTimeInMillis());
        courseBo.setStartDateStart(e.getStartDateStart() == null ? Constant.DEFAULTNULL : e.getStartDateStart().getTimeInMillis());
        courseBo.setStartTime1(e.getStartTime1());
        courseBo.setStartTime2(e.getStartTime2());
        courseBo.setStartUponArrival(e.getStartUponArrival());
        courseBo.setStatus(e.getStatus());
        courseBo.setStatusSet(e.getStatusSet());
        courseBo.setStudyDayNote(e.getStudyDayNote());
        courseBo.setSuitableStudent(e.getSuitableStudent());
        if (e.getTeacherList() != null) {
            List<TeacherBo> list = new ArrayList<>();
            for (TeacherEntityExt a : e.getTeacherList()) {
                list.add(TeacherConverter.toBo(a));
            }
            courseBo.setTeacherList(list);
        }
        courseBo.setTeachingAndExercise(e.getTeachingAndExercise());
        courseBo.setTeachingMaterialFee(e.getTeachingMaterialFee());
        courseBo.setTeachingMaterialIntro(e.getTeachingMaterialIntro());
        courseBo.setTeachingMethod(e.getTeachingMethod());
        courseBo.setTrail(e.getTrail());
        courseBo.setWholeName(e.getWholeName());
        return courseBo;
    }

    public static CourseEntityExt fromBo(CourseBo bo) {
        CourseEntityExt courseEntityExt = new CourseEntityExt();
        courseEntityExt.setAddress(bo.getAddress());
        courseEntityExt.setAddressId(bo.getAddressId());
        courseEntityExt.setAddressLat(bo.getAddressLat());
        courseEntityExt.setAddressLng(bo.getAddressLng());
        courseEntityExt.setAssignments(bo.getAssignments());
        courseEntityExt.setBonusService(bo.getBonusService());
        courseEntityExt.setBookingTotal(bo.getBookingTotal());
        courseEntityExt.setBookingType(bo.getBookingType());
        courseEntityExt.setCashback(bo.getCashback());
        courseEntityExt.setCashbackDate(DateUtility.getTimeFromLong(bo.getCashbackDate()));
        courseEntityExt.setCashbackDateStart(DateUtility.getTimeFromLong(bo.getCashbackDateStart()));
        courseEntityExt.setCashbackDateEnd(DateUtility.getTimeFromLong(bo.getCashbackDateEnd()));
        courseEntityExt.setCashbackEnd(bo.getCashbackEnd());
        courseEntityExt.setCashbackStart(bo.getCashbackStart());
        courseEntityExt.setCategoryId(bo.getCategoryId());
        courseEntityExt.setCategoryIdSet(bo.getCategoryIdSet());
        courseEntityExt.setCategoryName(bo.getCategoryName());
        courseEntityExt.setCategoryRank(bo.getCategoryRank());
        courseEntityExt.setCategoryValue(bo.getCategoryValue());
        courseEntityExt.setCertification(bo.getCertification());
        courseEntityExt.setCircleId(bo.getCircleId());
        courseEntityExt.setCircleIdSet(bo.getCircleIdSet());
        courseEntityExt.setCircleName(bo.getCircleName());
        courseEntityExt.setCircleValue(bo.getCircleValue());
        if (bo.getClassPhotoList() != null) {
            List<ClassPhotoEntityExt> list = new ArrayList<>();
            for (ClassPhotoBo a : bo.getClassPhotoList()) {
                list.add(ClassPhotoConverter.fromBo(a));
            }
            courseEntityExt.setClassPhotoList(list);
        }
        courseEntityExt.setClassSize(bo.getClassSize());
        courseEntityExt.setClassTeacher(bo.getClassTeacher());
        courseEntityExt.setClassType(bo.getClassType());
        courseEntityExt.setClassTypeSet(bo.getClassTypeSet());
        courseEntityExt.setCommission(bo.getCommission());
        courseEntityExt.setContact(bo.getContact());
        courseEntityExt.setCourseHourLength(bo.getCourseHourLength());
        courseEntityExt.setCourseHourNum(bo.getCourseHourNum());
        courseEntityExt.setCourseHourNumEnd(bo.getCourseHourNumEnd());
        courseEntityExt.setCourseHourNumSet(bo.getCourseHourNumSet());
        courseEntityExt.setCourseHourNumStart(bo.getCourseHourNumStart());
        courseEntityExt.setCourseIntro(bo.getCourseIntro());
        courseEntityExt.setCourseName(bo.getCourseName());
        courseEntityExt.setCourseTemplateId(bo.getCourseTemplateId());
        courseEntityExt.setCourseTemplateIdSet(bo.getCourseTemplateIdSet());
        courseEntityExt.setCreateTime(DateUtility.getTimeFromLong(bo.getCreateTime()));
        courseEntityExt.setCreateTimeEnd(DateUtility.getTimeFromLong(bo.getCreateTimeEnd()));
        courseEntityExt.setCreateTimeStart(DateUtility.getTimeFromLong(bo.getCreateTimeStart()));
        courseEntityExt.setCutoffDate(DateUtility.getTimeFromLong(bo.getCutoffDate()));
        courseEntityExt.setCutoffDateEnd(DateUtility.getTimeFromLong(bo.getCutoffDateEnd()));
        courseEntityExt.setCutoffDateStart(DateUtility.getTimeFromLong(bo.getCutoffDateStart()));
        courseEntityExt.setDiscount(bo.getDiscount());
        courseEntityExt.setDiscountEnd(bo.getDiscountEnd());
        courseEntityExt.setDiscountStart(bo.getDiscountStart());
        courseEntityExt.setDownloadMaterials(bo.getDownloadMaterials());
        courseEntityExt.setEnabled(bo.getEnabled());
        courseEntityExt.setExtracurricular(bo.getExtracurricular());
        courseEntityExt.setFinishDate(DateUtility.getTimeFromLong(bo.getFinishDate()));
        courseEntityExt.setFinishDateEnd(DateUtility.getTimeFromLong(bo.getFinishDateEnd()));
        courseEntityExt.setFinishDateStart(DateUtility.getTimeFromLong(bo.getFinishDateStart()));
        courseEntityExt.setFinishTime1(bo.getFinishTime1());
        courseEntityExt.setFinishTime2(bo.getFinishTime2());
        courseEntityExt.setGoal(bo.getGoal());
        courseEntityExt.setHighScoreReward(bo.getHighScoreReward());
        courseEntityExt.setId(bo.getId());
        courseEntityExt.setIdSet(bo.getIdSet());
        courseEntityExt.setInstName(bo.getInstName());
        courseEntityExt.setLastModifyTime(DateUtility.getTimeFromLong(bo.getLastModifyTime()));
        courseEntityExt.setLastModifyTimeEnd(DateUtility.getTimeFromLong(bo.getLastModifyTimeEnd()));
        courseEntityExt.setLastModifyTimeStart(DateUtility.getTimeFromLong(bo.getLastModifyTimeStart()));
        courseEntityExt.setLocationId(bo.getLocationId());
        courseEntityExt.setLocationIdSet(bo.getLocationIdSet());
        courseEntityExt.setLocationName(bo.getLocationName());
        courseEntityExt.setLocationValue(bo.getLocationValue());
        courseEntityExt.setLogoUrl(bo.getLogoUrl());
        courseEntityExt.setMarking(bo.getMarking());
        courseEntityExt.setNoRefundDate(DateUtility.getTimeFromLong(bo.getNoRefundDate()));
        courseEntityExt.setNoRefundDateStart(DateUtility.getTimeFromLong(bo.getNoRefundDateStart()));
        courseEntityExt.setNoRefundDateEnd(DateUtility.getTimeFromLong(bo.getNoRefundDateEnd()));
        courseEntityExt.setOpenCourseRequirement(bo.getOpenCourseRequirement());
        courseEntityExt.setOriginalPrice(bo.getOriginalPrice());
        courseEntityExt.setOriginalPriceEnd(bo.getOriginalPriceEnd());
        courseEntityExt.setOriginalPriceStart(bo.getOriginalPriceStart());
        courseEntityExt.setOutline(bo.getOutline());
        courseEntityExt.setPartnerDistinction(bo.getPartnerDistinction());
        courseEntityExt.setPartnerId(bo.getPartnerId());
        courseEntityExt.setPartnerIdSet(bo.getPartnerIdSet());
        courseEntityExt.setPartnerIntro(bo.getPartnerIntro());
        courseEntityExt.setPartnerQualification(bo.getPartnerQualification());
        courseEntityExt.setPartnerRating(bo.getPartnerRating());
        courseEntityExt.setPassAgreement(bo.getPassAgreement());
        courseEntityExt.setPopularity(bo.getPopularity());
        courseEntityExt.setPopularityEnd(bo.getPopularityEnd());
        courseEntityExt.setPopularitySet(bo.getPopularitySet());
        courseEntityExt.setPopularityStart(bo.getPopularityStart());
        courseEntityExt.setQualityAssurance(bo.getQualityAssurance());
        courseEntityExt.setQuestionBank(bo.getQuestionBank());
        courseEntityExt.setQuestionSession(bo.getQuestionSession());
        courseEntityExt.setQuiz(bo.getQuiz());
        courseEntityExt.setRating(bo.getRating());
        courseEntityExt.setReference(bo.getReference());
        courseEntityExt.setRegLocation(bo.getRegLocation());
        courseEntityExt.setRegPhone(bo.getRegPhone());
        courseEntityExt.setSchooltimeDay(bo.getSchooltimeDay());
        courseEntityExt.setSchooltimeDaySet(bo.getSchooltimeDaySet());
        courseEntityExt.setSchooltimeWeek(bo.getSchooltimeWeek());
        courseEntityExt.setSchooltimeWeekSet(bo.getSchooltimeWeekSet());
        courseEntityExt.setServiceCharge(bo.getServiceCharge());
        courseEntityExt.setStartDate(DateUtility.getTimeFromLong(bo.getStartDate()));
        courseEntityExt.setStartDateEnd(DateUtility.getTimeFromLong(bo.getStartDateEnd()));
        courseEntityExt.setStartDateStart(DateUtility.getTimeFromLong(bo.getStartDateStart()));
        courseEntityExt.setStartTime1(bo.getStartTime1());
        courseEntityExt.setStartTime2(bo.getStartTime2());
        courseEntityExt.setStartUponArrival(bo.getStartUponArrival());
        courseEntityExt.setStatus(bo.getStatus());
        courseEntityExt.setStatusSet(bo.getStatusSet());
        courseEntityExt.setStudyDayNote(bo.getStudyDayNote());
        courseEntityExt.setSuitableStudent(bo.getSuitableStudent());
        if (bo.getTeacherList() != null) {
            List<TeacherEntityExt> list = new ArrayList<>();
            for (TeacherBo a : bo.getTeacherList()) {
                list.add(TeacherConverter.fromBo(a));
            }
            courseEntityExt.setTeacherList(list);
        }
        courseEntityExt.setTeachingAndExercise(bo.getTeachingAndExercise());
        courseEntityExt.setTeachingMaterialFee(bo.getTeachingMaterialFee());
        courseEntityExt.setTeachingMaterialIntro(bo.getTeachingMaterialIntro());
        courseEntityExt.setTeachingMethod(bo.getTeachingMethod());
        courseEntityExt.setTrail(bo.getTrail());
        courseEntityExt.setWholeName(bo.getWholeName());
        return courseEntityExt;
    }
}
