/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.ishangke.edunav.commoncontract.model;

import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class UserLocationBo implements org.apache.thrift.TBase<UserLocationBo, UserLocationBo._Fields>, java.io.Serializable, Cloneable, Comparable<UserLocationBo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("UserLocationBo");

  private static final org.apache.thrift.protocol.TField ID_FIELD_DESC = new org.apache.thrift.protocol.TField("id", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField USER_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("userId", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField LOCATION_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("locationId", org.apache.thrift.protocol.TType.I32, (short)3);
  private static final org.apache.thrift.protocol.TField LAST_MODIFY_TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("lastModifyTime", org.apache.thrift.protocol.TType.I64, (short)4);
  private static final org.apache.thrift.protocol.TField ID_SET_FIELD_DESC = new org.apache.thrift.protocol.TField("idSet", org.apache.thrift.protocol.TType.SET, (short)5);
  private static final org.apache.thrift.protocol.TField LAST_MODIFY_TIME_START_FIELD_DESC = new org.apache.thrift.protocol.TField("lastModifyTimeStart", org.apache.thrift.protocol.TType.I64, (short)6);
  private static final org.apache.thrift.protocol.TField LAST_MODIFY_TIME_END_FIELD_DESC = new org.apache.thrift.protocol.TField("lastModifyTimeEnd", org.apache.thrift.protocol.TType.I64, (short)7);
  private static final org.apache.thrift.protocol.TField CREATE_TIME_START_FIELD_DESC = new org.apache.thrift.protocol.TField("createTimeStart", org.apache.thrift.protocol.TType.I64, (short)8);
  private static final org.apache.thrift.protocol.TField CREATE_TIME_END_FIELD_DESC = new org.apache.thrift.protocol.TField("createTimeEnd", org.apache.thrift.protocol.TType.I64, (short)9);
  private static final org.apache.thrift.protocol.TField LAST_LOGIN_TIME_START_FIELD_DESC = new org.apache.thrift.protocol.TField("lastLoginTimeStart", org.apache.thrift.protocol.TType.I64, (short)10);
  private static final org.apache.thrift.protocol.TField LAST_LOGIN_TIME_END_FIELD_DESC = new org.apache.thrift.protocol.TField("lastLoginTimeEnd", org.apache.thrift.protocol.TType.I64, (short)11);
  private static final org.apache.thrift.protocol.TField BIRTHDAY_START_FIELD_DESC = new org.apache.thrift.protocol.TField("birthdayStart", org.apache.thrift.protocol.TType.I64, (short)12);
  private static final org.apache.thrift.protocol.TField BIRTHDAY_END_FIELD_DESC = new org.apache.thrift.protocol.TField("birthdayEnd", org.apache.thrift.protocol.TType.I64, (short)13);
  private static final org.apache.thrift.protocol.TField USER_ID_SET_FIELD_DESC = new org.apache.thrift.protocol.TField("userIdSet", org.apache.thrift.protocol.TType.SET, (short)14);
  private static final org.apache.thrift.protocol.TField LOCATION_ID_SET_FIELD_DESC = new org.apache.thrift.protocol.TField("locationIdSet", org.apache.thrift.protocol.TType.SET, (short)15);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new UserLocationBoStandardSchemeFactory());
    schemes.put(TupleScheme.class, new UserLocationBoTupleSchemeFactory());
  }

  public int id; // required
  public int userId; // required
  public int locationId; // required
  public long lastModifyTime; // required
  public Set<Integer> idSet; // required
  public long lastModifyTimeStart; // required
  public long lastModifyTimeEnd; // required
  public long createTimeStart; // required
  public long createTimeEnd; // required
  public long lastLoginTimeStart; // required
  public long lastLoginTimeEnd; // required
  public long birthdayStart; // required
  public long birthdayEnd; // required
  public Set<Integer> userIdSet; // required
  public Set<Integer> locationIdSet; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ID((short)1, "id"),
    USER_ID((short)2, "userId"),
    LOCATION_ID((short)3, "locationId"),
    LAST_MODIFY_TIME((short)4, "lastModifyTime"),
    ID_SET((short)5, "idSet"),
    LAST_MODIFY_TIME_START((short)6, "lastModifyTimeStart"),
    LAST_MODIFY_TIME_END((short)7, "lastModifyTimeEnd"),
    CREATE_TIME_START((short)8, "createTimeStart"),
    CREATE_TIME_END((short)9, "createTimeEnd"),
    LAST_LOGIN_TIME_START((short)10, "lastLoginTimeStart"),
    LAST_LOGIN_TIME_END((short)11, "lastLoginTimeEnd"),
    BIRTHDAY_START((short)12, "birthdayStart"),
    BIRTHDAY_END((short)13, "birthdayEnd"),
    USER_ID_SET((short)14, "userIdSet"),
    LOCATION_ID_SET((short)15, "locationIdSet");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ID
          return ID;
        case 2: // USER_ID
          return USER_ID;
        case 3: // LOCATION_ID
          return LOCATION_ID;
        case 4: // LAST_MODIFY_TIME
          return LAST_MODIFY_TIME;
        case 5: // ID_SET
          return ID_SET;
        case 6: // LAST_MODIFY_TIME_START
          return LAST_MODIFY_TIME_START;
        case 7: // LAST_MODIFY_TIME_END
          return LAST_MODIFY_TIME_END;
        case 8: // CREATE_TIME_START
          return CREATE_TIME_START;
        case 9: // CREATE_TIME_END
          return CREATE_TIME_END;
        case 10: // LAST_LOGIN_TIME_START
          return LAST_LOGIN_TIME_START;
        case 11: // LAST_LOGIN_TIME_END
          return LAST_LOGIN_TIME_END;
        case 12: // BIRTHDAY_START
          return BIRTHDAY_START;
        case 13: // BIRTHDAY_END
          return BIRTHDAY_END;
        case 14: // USER_ID_SET
          return USER_ID_SET;
        case 15: // LOCATION_ID_SET
          return LOCATION_ID_SET;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ID_ISSET_ID = 0;
  private static final int __USERID_ISSET_ID = 1;
  private static final int __LOCATIONID_ISSET_ID = 2;
  private static final int __LASTMODIFYTIME_ISSET_ID = 3;
  private static final int __LASTMODIFYTIMESTART_ISSET_ID = 4;
  private static final int __LASTMODIFYTIMEEND_ISSET_ID = 5;
  private static final int __CREATETIMESTART_ISSET_ID = 6;
  private static final int __CREATETIMEEND_ISSET_ID = 7;
  private static final int __LASTLOGINTIMESTART_ISSET_ID = 8;
  private static final int __LASTLOGINTIMEEND_ISSET_ID = 9;
  private static final int __BIRTHDAYSTART_ISSET_ID = 10;
  private static final int __BIRTHDAYEND_ISSET_ID = 11;
  private short __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ID, new org.apache.thrift.meta_data.FieldMetaData("id", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.USER_ID, new org.apache.thrift.meta_data.FieldMetaData("userId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.LOCATION_ID, new org.apache.thrift.meta_data.FieldMetaData("locationId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.LAST_MODIFY_TIME, new org.apache.thrift.meta_data.FieldMetaData("lastModifyTime", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.ID_SET, new org.apache.thrift.meta_data.FieldMetaData("idSet", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.SetMetaData(org.apache.thrift.protocol.TType.SET, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32))));
    tmpMap.put(_Fields.LAST_MODIFY_TIME_START, new org.apache.thrift.meta_data.FieldMetaData("lastModifyTimeStart", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.LAST_MODIFY_TIME_END, new org.apache.thrift.meta_data.FieldMetaData("lastModifyTimeEnd", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.CREATE_TIME_START, new org.apache.thrift.meta_data.FieldMetaData("createTimeStart", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.CREATE_TIME_END, new org.apache.thrift.meta_data.FieldMetaData("createTimeEnd", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.LAST_LOGIN_TIME_START, new org.apache.thrift.meta_data.FieldMetaData("lastLoginTimeStart", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.LAST_LOGIN_TIME_END, new org.apache.thrift.meta_data.FieldMetaData("lastLoginTimeEnd", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.BIRTHDAY_START, new org.apache.thrift.meta_data.FieldMetaData("birthdayStart", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.BIRTHDAY_END, new org.apache.thrift.meta_data.FieldMetaData("birthdayEnd", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.USER_ID_SET, new org.apache.thrift.meta_data.FieldMetaData("userIdSet", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.SetMetaData(org.apache.thrift.protocol.TType.SET, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32))));
    tmpMap.put(_Fields.LOCATION_ID_SET, new org.apache.thrift.meta_data.FieldMetaData("locationIdSet", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.SetMetaData(org.apache.thrift.protocol.TType.SET, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(UserLocationBo.class, metaDataMap);
  }

  public UserLocationBo() {
  }

  public UserLocationBo(
    int id,
    int userId,
    int locationId,
    long lastModifyTime,
    Set<Integer> idSet,
    long lastModifyTimeStart,
    long lastModifyTimeEnd,
    long createTimeStart,
    long createTimeEnd,
    long lastLoginTimeStart,
    long lastLoginTimeEnd,
    long birthdayStart,
    long birthdayEnd,
    Set<Integer> userIdSet,
    Set<Integer> locationIdSet)
  {
    this();
    this.id = id;
    setIdIsSet(true);
    this.userId = userId;
    setUserIdIsSet(true);
    this.locationId = locationId;
    setLocationIdIsSet(true);
    this.lastModifyTime = lastModifyTime;
    setLastModifyTimeIsSet(true);
    this.idSet = idSet;
    this.lastModifyTimeStart = lastModifyTimeStart;
    setLastModifyTimeStartIsSet(true);
    this.lastModifyTimeEnd = lastModifyTimeEnd;
    setLastModifyTimeEndIsSet(true);
    this.createTimeStart = createTimeStart;
    setCreateTimeStartIsSet(true);
    this.createTimeEnd = createTimeEnd;
    setCreateTimeEndIsSet(true);
    this.lastLoginTimeStart = lastLoginTimeStart;
    setLastLoginTimeStartIsSet(true);
    this.lastLoginTimeEnd = lastLoginTimeEnd;
    setLastLoginTimeEndIsSet(true);
    this.birthdayStart = birthdayStart;
    setBirthdayStartIsSet(true);
    this.birthdayEnd = birthdayEnd;
    setBirthdayEndIsSet(true);
    this.userIdSet = userIdSet;
    this.locationIdSet = locationIdSet;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public UserLocationBo(UserLocationBo other) {
    __isset_bitfield = other.__isset_bitfield;
    this.id = other.id;
    this.userId = other.userId;
    this.locationId = other.locationId;
    this.lastModifyTime = other.lastModifyTime;
    if (other.isSetIdSet()) {
      Set<Integer> __this__idSet = new HashSet<Integer>(other.idSet);
      this.idSet = __this__idSet;
    }
    this.lastModifyTimeStart = other.lastModifyTimeStart;
    this.lastModifyTimeEnd = other.lastModifyTimeEnd;
    this.createTimeStart = other.createTimeStart;
    this.createTimeEnd = other.createTimeEnd;
    this.lastLoginTimeStart = other.lastLoginTimeStart;
    this.lastLoginTimeEnd = other.lastLoginTimeEnd;
    this.birthdayStart = other.birthdayStart;
    this.birthdayEnd = other.birthdayEnd;
    if (other.isSetUserIdSet()) {
      Set<Integer> __this__userIdSet = new HashSet<Integer>(other.userIdSet);
      this.userIdSet = __this__userIdSet;
    }
    if (other.isSetLocationIdSet()) {
      Set<Integer> __this__locationIdSet = new HashSet<Integer>(other.locationIdSet);
      this.locationIdSet = __this__locationIdSet;
    }
  }

  public UserLocationBo deepCopy() {
    return new UserLocationBo(this);
  }

  @Override
  public void clear() {
    setIdIsSet(false);
    this.id = 0;
    setUserIdIsSet(false);
    this.userId = 0;
    setLocationIdIsSet(false);
    this.locationId = 0;
    setLastModifyTimeIsSet(false);
    this.lastModifyTime = 0;
    this.idSet = null;
    setLastModifyTimeStartIsSet(false);
    this.lastModifyTimeStart = 0;
    setLastModifyTimeEndIsSet(false);
    this.lastModifyTimeEnd = 0;
    setCreateTimeStartIsSet(false);
    this.createTimeStart = 0;
    setCreateTimeEndIsSet(false);
    this.createTimeEnd = 0;
    setLastLoginTimeStartIsSet(false);
    this.lastLoginTimeStart = 0;
    setLastLoginTimeEndIsSet(false);
    this.lastLoginTimeEnd = 0;
    setBirthdayStartIsSet(false);
    this.birthdayStart = 0;
    setBirthdayEndIsSet(false);
    this.birthdayEnd = 0;
    this.userIdSet = null;
    this.locationIdSet = null;
  }

  public int getId() {
    return this.id;
  }

  public UserLocationBo setId(int id) {
    this.id = id;
    setIdIsSet(true);
    return this;
  }

  public void unsetId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __ID_ISSET_ID);
  }

  /** Returns true if field id is set (has been assigned a value) and false otherwise */
  public boolean isSetId() {
    return EncodingUtils.testBit(__isset_bitfield, __ID_ISSET_ID);
  }

  public void setIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __ID_ISSET_ID, value);
  }

  public int getUserId() {
    return this.userId;
  }

  public UserLocationBo setUserId(int userId) {
    this.userId = userId;
    setUserIdIsSet(true);
    return this;
  }

  public void unsetUserId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __USERID_ISSET_ID);
  }

  /** Returns true if field userId is set (has been assigned a value) and false otherwise */
  public boolean isSetUserId() {
    return EncodingUtils.testBit(__isset_bitfield, __USERID_ISSET_ID);
  }

  public void setUserIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __USERID_ISSET_ID, value);
  }

  public int getLocationId() {
    return this.locationId;
  }

  public UserLocationBo setLocationId(int locationId) {
    this.locationId = locationId;
    setLocationIdIsSet(true);
    return this;
  }

  public void unsetLocationId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __LOCATIONID_ISSET_ID);
  }

  /** Returns true if field locationId is set (has been assigned a value) and false otherwise */
  public boolean isSetLocationId() {
    return EncodingUtils.testBit(__isset_bitfield, __LOCATIONID_ISSET_ID);
  }

  public void setLocationIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __LOCATIONID_ISSET_ID, value);
  }

  public long getLastModifyTime() {
    return this.lastModifyTime;
  }

  public UserLocationBo setLastModifyTime(long lastModifyTime) {
    this.lastModifyTime = lastModifyTime;
    setLastModifyTimeIsSet(true);
    return this;
  }

  public void unsetLastModifyTime() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __LASTMODIFYTIME_ISSET_ID);
  }

  /** Returns true if field lastModifyTime is set (has been assigned a value) and false otherwise */
  public boolean isSetLastModifyTime() {
    return EncodingUtils.testBit(__isset_bitfield, __LASTMODIFYTIME_ISSET_ID);
  }

  public void setLastModifyTimeIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __LASTMODIFYTIME_ISSET_ID, value);
  }

  public int getIdSetSize() {
    return (this.idSet == null) ? 0 : this.idSet.size();
  }

  public java.util.Iterator<Integer> getIdSetIterator() {
    return (this.idSet == null) ? null : this.idSet.iterator();
  }

  public void addToIdSet(int elem) {
    if (this.idSet == null) {
      this.idSet = new HashSet<Integer>();
    }
    this.idSet.add(elem);
  }

  public Set<Integer> getIdSet() {
    return this.idSet;
  }

  public UserLocationBo setIdSet(Set<Integer> idSet) {
    this.idSet = idSet;
    return this;
  }

  public void unsetIdSet() {
    this.idSet = null;
  }

  /** Returns true if field idSet is set (has been assigned a value) and false otherwise */
  public boolean isSetIdSet() {
    return this.idSet != null;
  }

  public void setIdSetIsSet(boolean value) {
    if (!value) {
      this.idSet = null;
    }
  }

  public long getLastModifyTimeStart() {
    return this.lastModifyTimeStart;
  }

  public UserLocationBo setLastModifyTimeStart(long lastModifyTimeStart) {
    this.lastModifyTimeStart = lastModifyTimeStart;
    setLastModifyTimeStartIsSet(true);
    return this;
  }

  public void unsetLastModifyTimeStart() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __LASTMODIFYTIMESTART_ISSET_ID);
  }

  /** Returns true if field lastModifyTimeStart is set (has been assigned a value) and false otherwise */
  public boolean isSetLastModifyTimeStart() {
    return EncodingUtils.testBit(__isset_bitfield, __LASTMODIFYTIMESTART_ISSET_ID);
  }

  public void setLastModifyTimeStartIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __LASTMODIFYTIMESTART_ISSET_ID, value);
  }

  public long getLastModifyTimeEnd() {
    return this.lastModifyTimeEnd;
  }

  public UserLocationBo setLastModifyTimeEnd(long lastModifyTimeEnd) {
    this.lastModifyTimeEnd = lastModifyTimeEnd;
    setLastModifyTimeEndIsSet(true);
    return this;
  }

  public void unsetLastModifyTimeEnd() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __LASTMODIFYTIMEEND_ISSET_ID);
  }

  /** Returns true if field lastModifyTimeEnd is set (has been assigned a value) and false otherwise */
  public boolean isSetLastModifyTimeEnd() {
    return EncodingUtils.testBit(__isset_bitfield, __LASTMODIFYTIMEEND_ISSET_ID);
  }

  public void setLastModifyTimeEndIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __LASTMODIFYTIMEEND_ISSET_ID, value);
  }

  public long getCreateTimeStart() {
    return this.createTimeStart;
  }

  public UserLocationBo setCreateTimeStart(long createTimeStart) {
    this.createTimeStart = createTimeStart;
    setCreateTimeStartIsSet(true);
    return this;
  }

  public void unsetCreateTimeStart() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __CREATETIMESTART_ISSET_ID);
  }

  /** Returns true if field createTimeStart is set (has been assigned a value) and false otherwise */
  public boolean isSetCreateTimeStart() {
    return EncodingUtils.testBit(__isset_bitfield, __CREATETIMESTART_ISSET_ID);
  }

  public void setCreateTimeStartIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __CREATETIMESTART_ISSET_ID, value);
  }

  public long getCreateTimeEnd() {
    return this.createTimeEnd;
  }

  public UserLocationBo setCreateTimeEnd(long createTimeEnd) {
    this.createTimeEnd = createTimeEnd;
    setCreateTimeEndIsSet(true);
    return this;
  }

  public void unsetCreateTimeEnd() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __CREATETIMEEND_ISSET_ID);
  }

  /** Returns true if field createTimeEnd is set (has been assigned a value) and false otherwise */
  public boolean isSetCreateTimeEnd() {
    return EncodingUtils.testBit(__isset_bitfield, __CREATETIMEEND_ISSET_ID);
  }

  public void setCreateTimeEndIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __CREATETIMEEND_ISSET_ID, value);
  }

  public long getLastLoginTimeStart() {
    return this.lastLoginTimeStart;
  }

  public UserLocationBo setLastLoginTimeStart(long lastLoginTimeStart) {
    this.lastLoginTimeStart = lastLoginTimeStart;
    setLastLoginTimeStartIsSet(true);
    return this;
  }

  public void unsetLastLoginTimeStart() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __LASTLOGINTIMESTART_ISSET_ID);
  }

  /** Returns true if field lastLoginTimeStart is set (has been assigned a value) and false otherwise */
  public boolean isSetLastLoginTimeStart() {
    return EncodingUtils.testBit(__isset_bitfield, __LASTLOGINTIMESTART_ISSET_ID);
  }

  public void setLastLoginTimeStartIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __LASTLOGINTIMESTART_ISSET_ID, value);
  }

  public long getLastLoginTimeEnd() {
    return this.lastLoginTimeEnd;
  }

  public UserLocationBo setLastLoginTimeEnd(long lastLoginTimeEnd) {
    this.lastLoginTimeEnd = lastLoginTimeEnd;
    setLastLoginTimeEndIsSet(true);
    return this;
  }

  public void unsetLastLoginTimeEnd() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __LASTLOGINTIMEEND_ISSET_ID);
  }

  /** Returns true if field lastLoginTimeEnd is set (has been assigned a value) and false otherwise */
  public boolean isSetLastLoginTimeEnd() {
    return EncodingUtils.testBit(__isset_bitfield, __LASTLOGINTIMEEND_ISSET_ID);
  }

  public void setLastLoginTimeEndIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __LASTLOGINTIMEEND_ISSET_ID, value);
  }

  public long getBirthdayStart() {
    return this.birthdayStart;
  }

  public UserLocationBo setBirthdayStart(long birthdayStart) {
    this.birthdayStart = birthdayStart;
    setBirthdayStartIsSet(true);
    return this;
  }

  public void unsetBirthdayStart() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __BIRTHDAYSTART_ISSET_ID);
  }

  /** Returns true if field birthdayStart is set (has been assigned a value) and false otherwise */
  public boolean isSetBirthdayStart() {
    return EncodingUtils.testBit(__isset_bitfield, __BIRTHDAYSTART_ISSET_ID);
  }

  public void setBirthdayStartIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __BIRTHDAYSTART_ISSET_ID, value);
  }

  public long getBirthdayEnd() {
    return this.birthdayEnd;
  }

  public UserLocationBo setBirthdayEnd(long birthdayEnd) {
    this.birthdayEnd = birthdayEnd;
    setBirthdayEndIsSet(true);
    return this;
  }

  public void unsetBirthdayEnd() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __BIRTHDAYEND_ISSET_ID);
  }

  /** Returns true if field birthdayEnd is set (has been assigned a value) and false otherwise */
  public boolean isSetBirthdayEnd() {
    return EncodingUtils.testBit(__isset_bitfield, __BIRTHDAYEND_ISSET_ID);
  }

  public void setBirthdayEndIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __BIRTHDAYEND_ISSET_ID, value);
  }

  public int getUserIdSetSize() {
    return (this.userIdSet == null) ? 0 : this.userIdSet.size();
  }

  public java.util.Iterator<Integer> getUserIdSetIterator() {
    return (this.userIdSet == null) ? null : this.userIdSet.iterator();
  }

  public void addToUserIdSet(int elem) {
    if (this.userIdSet == null) {
      this.userIdSet = new HashSet<Integer>();
    }
    this.userIdSet.add(elem);
  }

  public Set<Integer> getUserIdSet() {
    return this.userIdSet;
  }

  public UserLocationBo setUserIdSet(Set<Integer> userIdSet) {
    this.userIdSet = userIdSet;
    return this;
  }

  public void unsetUserIdSet() {
    this.userIdSet = null;
  }

  /** Returns true if field userIdSet is set (has been assigned a value) and false otherwise */
  public boolean isSetUserIdSet() {
    return this.userIdSet != null;
  }

  public void setUserIdSetIsSet(boolean value) {
    if (!value) {
      this.userIdSet = null;
    }
  }

  public int getLocationIdSetSize() {
    return (this.locationIdSet == null) ? 0 : this.locationIdSet.size();
  }

  public java.util.Iterator<Integer> getLocationIdSetIterator() {
    return (this.locationIdSet == null) ? null : this.locationIdSet.iterator();
  }

  public void addToLocationIdSet(int elem) {
    if (this.locationIdSet == null) {
      this.locationIdSet = new HashSet<Integer>();
    }
    this.locationIdSet.add(elem);
  }

  public Set<Integer> getLocationIdSet() {
    return this.locationIdSet;
  }

  public UserLocationBo setLocationIdSet(Set<Integer> locationIdSet) {
    this.locationIdSet = locationIdSet;
    return this;
  }

  public void unsetLocationIdSet() {
    this.locationIdSet = null;
  }

  /** Returns true if field locationIdSet is set (has been assigned a value) and false otherwise */
  public boolean isSetLocationIdSet() {
    return this.locationIdSet != null;
  }

  public void setLocationIdSetIsSet(boolean value) {
    if (!value) {
      this.locationIdSet = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case ID:
      if (value == null) {
        unsetId();
      } else {
        setId((Integer)value);
      }
      break;

    case USER_ID:
      if (value == null) {
        unsetUserId();
      } else {
        setUserId((Integer)value);
      }
      break;

    case LOCATION_ID:
      if (value == null) {
        unsetLocationId();
      } else {
        setLocationId((Integer)value);
      }
      break;

    case LAST_MODIFY_TIME:
      if (value == null) {
        unsetLastModifyTime();
      } else {
        setLastModifyTime((Long)value);
      }
      break;

    case ID_SET:
      if (value == null) {
        unsetIdSet();
      } else {
        setIdSet((Set<Integer>)value);
      }
      break;

    case LAST_MODIFY_TIME_START:
      if (value == null) {
        unsetLastModifyTimeStart();
      } else {
        setLastModifyTimeStart((Long)value);
      }
      break;

    case LAST_MODIFY_TIME_END:
      if (value == null) {
        unsetLastModifyTimeEnd();
      } else {
        setLastModifyTimeEnd((Long)value);
      }
      break;

    case CREATE_TIME_START:
      if (value == null) {
        unsetCreateTimeStart();
      } else {
        setCreateTimeStart((Long)value);
      }
      break;

    case CREATE_TIME_END:
      if (value == null) {
        unsetCreateTimeEnd();
      } else {
        setCreateTimeEnd((Long)value);
      }
      break;

    case LAST_LOGIN_TIME_START:
      if (value == null) {
        unsetLastLoginTimeStart();
      } else {
        setLastLoginTimeStart((Long)value);
      }
      break;

    case LAST_LOGIN_TIME_END:
      if (value == null) {
        unsetLastLoginTimeEnd();
      } else {
        setLastLoginTimeEnd((Long)value);
      }
      break;

    case BIRTHDAY_START:
      if (value == null) {
        unsetBirthdayStart();
      } else {
        setBirthdayStart((Long)value);
      }
      break;

    case BIRTHDAY_END:
      if (value == null) {
        unsetBirthdayEnd();
      } else {
        setBirthdayEnd((Long)value);
      }
      break;

    case USER_ID_SET:
      if (value == null) {
        unsetUserIdSet();
      } else {
        setUserIdSet((Set<Integer>)value);
      }
      break;

    case LOCATION_ID_SET:
      if (value == null) {
        unsetLocationIdSet();
      } else {
        setLocationIdSet((Set<Integer>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ID:
      return Integer.valueOf(getId());

    case USER_ID:
      return Integer.valueOf(getUserId());

    case LOCATION_ID:
      return Integer.valueOf(getLocationId());

    case LAST_MODIFY_TIME:
      return Long.valueOf(getLastModifyTime());

    case ID_SET:
      return getIdSet();

    case LAST_MODIFY_TIME_START:
      return Long.valueOf(getLastModifyTimeStart());

    case LAST_MODIFY_TIME_END:
      return Long.valueOf(getLastModifyTimeEnd());

    case CREATE_TIME_START:
      return Long.valueOf(getCreateTimeStart());

    case CREATE_TIME_END:
      return Long.valueOf(getCreateTimeEnd());

    case LAST_LOGIN_TIME_START:
      return Long.valueOf(getLastLoginTimeStart());

    case LAST_LOGIN_TIME_END:
      return Long.valueOf(getLastLoginTimeEnd());

    case BIRTHDAY_START:
      return Long.valueOf(getBirthdayStart());

    case BIRTHDAY_END:
      return Long.valueOf(getBirthdayEnd());

    case USER_ID_SET:
      return getUserIdSet();

    case LOCATION_ID_SET:
      return getLocationIdSet();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ID:
      return isSetId();
    case USER_ID:
      return isSetUserId();
    case LOCATION_ID:
      return isSetLocationId();
    case LAST_MODIFY_TIME:
      return isSetLastModifyTime();
    case ID_SET:
      return isSetIdSet();
    case LAST_MODIFY_TIME_START:
      return isSetLastModifyTimeStart();
    case LAST_MODIFY_TIME_END:
      return isSetLastModifyTimeEnd();
    case CREATE_TIME_START:
      return isSetCreateTimeStart();
    case CREATE_TIME_END:
      return isSetCreateTimeEnd();
    case LAST_LOGIN_TIME_START:
      return isSetLastLoginTimeStart();
    case LAST_LOGIN_TIME_END:
      return isSetLastLoginTimeEnd();
    case BIRTHDAY_START:
      return isSetBirthdayStart();
    case BIRTHDAY_END:
      return isSetBirthdayEnd();
    case USER_ID_SET:
      return isSetUserIdSet();
    case LOCATION_ID_SET:
      return isSetLocationIdSet();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof UserLocationBo)
      return this.equals((UserLocationBo)that);
    return false;
  }

  public boolean equals(UserLocationBo that) {
    if (that == null)
      return false;

    boolean this_present_id = true;
    boolean that_present_id = true;
    if (this_present_id || that_present_id) {
      if (!(this_present_id && that_present_id))
        return false;
      if (this.id != that.id)
        return false;
    }

    boolean this_present_userId = true;
    boolean that_present_userId = true;
    if (this_present_userId || that_present_userId) {
      if (!(this_present_userId && that_present_userId))
        return false;
      if (this.userId != that.userId)
        return false;
    }

    boolean this_present_locationId = true;
    boolean that_present_locationId = true;
    if (this_present_locationId || that_present_locationId) {
      if (!(this_present_locationId && that_present_locationId))
        return false;
      if (this.locationId != that.locationId)
        return false;
    }

    boolean this_present_lastModifyTime = true;
    boolean that_present_lastModifyTime = true;
    if (this_present_lastModifyTime || that_present_lastModifyTime) {
      if (!(this_present_lastModifyTime && that_present_lastModifyTime))
        return false;
      if (this.lastModifyTime != that.lastModifyTime)
        return false;
    }

    boolean this_present_idSet = true && this.isSetIdSet();
    boolean that_present_idSet = true && that.isSetIdSet();
    if (this_present_idSet || that_present_idSet) {
      if (!(this_present_idSet && that_present_idSet))
        return false;
      if (!this.idSet.equals(that.idSet))
        return false;
    }

    boolean this_present_lastModifyTimeStart = true;
    boolean that_present_lastModifyTimeStart = true;
    if (this_present_lastModifyTimeStart || that_present_lastModifyTimeStart) {
      if (!(this_present_lastModifyTimeStart && that_present_lastModifyTimeStart))
        return false;
      if (this.lastModifyTimeStart != that.lastModifyTimeStart)
        return false;
    }

    boolean this_present_lastModifyTimeEnd = true;
    boolean that_present_lastModifyTimeEnd = true;
    if (this_present_lastModifyTimeEnd || that_present_lastModifyTimeEnd) {
      if (!(this_present_lastModifyTimeEnd && that_present_lastModifyTimeEnd))
        return false;
      if (this.lastModifyTimeEnd != that.lastModifyTimeEnd)
        return false;
    }

    boolean this_present_createTimeStart = true;
    boolean that_present_createTimeStart = true;
    if (this_present_createTimeStart || that_present_createTimeStart) {
      if (!(this_present_createTimeStart && that_present_createTimeStart))
        return false;
      if (this.createTimeStart != that.createTimeStart)
        return false;
    }

    boolean this_present_createTimeEnd = true;
    boolean that_present_createTimeEnd = true;
    if (this_present_createTimeEnd || that_present_createTimeEnd) {
      if (!(this_present_createTimeEnd && that_present_createTimeEnd))
        return false;
      if (this.createTimeEnd != that.createTimeEnd)
        return false;
    }

    boolean this_present_lastLoginTimeStart = true;
    boolean that_present_lastLoginTimeStart = true;
    if (this_present_lastLoginTimeStart || that_present_lastLoginTimeStart) {
      if (!(this_present_lastLoginTimeStart && that_present_lastLoginTimeStart))
        return false;
      if (this.lastLoginTimeStart != that.lastLoginTimeStart)
        return false;
    }

    boolean this_present_lastLoginTimeEnd = true;
    boolean that_present_lastLoginTimeEnd = true;
    if (this_present_lastLoginTimeEnd || that_present_lastLoginTimeEnd) {
      if (!(this_present_lastLoginTimeEnd && that_present_lastLoginTimeEnd))
        return false;
      if (this.lastLoginTimeEnd != that.lastLoginTimeEnd)
        return false;
    }

    boolean this_present_birthdayStart = true;
    boolean that_present_birthdayStart = true;
    if (this_present_birthdayStart || that_present_birthdayStart) {
      if (!(this_present_birthdayStart && that_present_birthdayStart))
        return false;
      if (this.birthdayStart != that.birthdayStart)
        return false;
    }

    boolean this_present_birthdayEnd = true;
    boolean that_present_birthdayEnd = true;
    if (this_present_birthdayEnd || that_present_birthdayEnd) {
      if (!(this_present_birthdayEnd && that_present_birthdayEnd))
        return false;
      if (this.birthdayEnd != that.birthdayEnd)
        return false;
    }

    boolean this_present_userIdSet = true && this.isSetUserIdSet();
    boolean that_present_userIdSet = true && that.isSetUserIdSet();
    if (this_present_userIdSet || that_present_userIdSet) {
      if (!(this_present_userIdSet && that_present_userIdSet))
        return false;
      if (!this.userIdSet.equals(that.userIdSet))
        return false;
    }

    boolean this_present_locationIdSet = true && this.isSetLocationIdSet();
    boolean that_present_locationIdSet = true && that.isSetLocationIdSet();
    if (this_present_locationIdSet || that_present_locationIdSet) {
      if (!(this_present_locationIdSet && that_present_locationIdSet))
        return false;
      if (!this.locationIdSet.equals(that.locationIdSet))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    HashCodeBuilder builder = new HashCodeBuilder();

    boolean present_id = true;
    builder.append(present_id);
    if (present_id)
      builder.append(id);

    boolean present_userId = true;
    builder.append(present_userId);
    if (present_userId)
      builder.append(userId);

    boolean present_locationId = true;
    builder.append(present_locationId);
    if (present_locationId)
      builder.append(locationId);

    boolean present_lastModifyTime = true;
    builder.append(present_lastModifyTime);
    if (present_lastModifyTime)
      builder.append(lastModifyTime);

    boolean present_idSet = true && (isSetIdSet());
    builder.append(present_idSet);
    if (present_idSet)
      builder.append(idSet);

    boolean present_lastModifyTimeStart = true;
    builder.append(present_lastModifyTimeStart);
    if (present_lastModifyTimeStart)
      builder.append(lastModifyTimeStart);

    boolean present_lastModifyTimeEnd = true;
    builder.append(present_lastModifyTimeEnd);
    if (present_lastModifyTimeEnd)
      builder.append(lastModifyTimeEnd);

    boolean present_createTimeStart = true;
    builder.append(present_createTimeStart);
    if (present_createTimeStart)
      builder.append(createTimeStart);

    boolean present_createTimeEnd = true;
    builder.append(present_createTimeEnd);
    if (present_createTimeEnd)
      builder.append(createTimeEnd);

    boolean present_lastLoginTimeStart = true;
    builder.append(present_lastLoginTimeStart);
    if (present_lastLoginTimeStart)
      builder.append(lastLoginTimeStart);

    boolean present_lastLoginTimeEnd = true;
    builder.append(present_lastLoginTimeEnd);
    if (present_lastLoginTimeEnd)
      builder.append(lastLoginTimeEnd);

    boolean present_birthdayStart = true;
    builder.append(present_birthdayStart);
    if (present_birthdayStart)
      builder.append(birthdayStart);

    boolean present_birthdayEnd = true;
    builder.append(present_birthdayEnd);
    if (present_birthdayEnd)
      builder.append(birthdayEnd);

    boolean present_userIdSet = true && (isSetUserIdSet());
    builder.append(present_userIdSet);
    if (present_userIdSet)
      builder.append(userIdSet);

    boolean present_locationIdSet = true && (isSetLocationIdSet());
    builder.append(present_locationIdSet);
    if (present_locationIdSet)
      builder.append(locationIdSet);

    return builder.toHashCode();
  }

  @Override
  public int compareTo(UserLocationBo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetId()).compareTo(other.isSetId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.id, other.id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUserId()).compareTo(other.isSetUserId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUserId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.userId, other.userId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLocationId()).compareTo(other.isSetLocationId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLocationId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.locationId, other.locationId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLastModifyTime()).compareTo(other.isSetLastModifyTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLastModifyTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.lastModifyTime, other.lastModifyTime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetIdSet()).compareTo(other.isSetIdSet());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIdSet()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.idSet, other.idSet);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLastModifyTimeStart()).compareTo(other.isSetLastModifyTimeStart());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLastModifyTimeStart()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.lastModifyTimeStart, other.lastModifyTimeStart);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLastModifyTimeEnd()).compareTo(other.isSetLastModifyTimeEnd());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLastModifyTimeEnd()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.lastModifyTimeEnd, other.lastModifyTimeEnd);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCreateTimeStart()).compareTo(other.isSetCreateTimeStart());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCreateTimeStart()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.createTimeStart, other.createTimeStart);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCreateTimeEnd()).compareTo(other.isSetCreateTimeEnd());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCreateTimeEnd()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.createTimeEnd, other.createTimeEnd);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLastLoginTimeStart()).compareTo(other.isSetLastLoginTimeStart());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLastLoginTimeStart()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.lastLoginTimeStart, other.lastLoginTimeStart);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLastLoginTimeEnd()).compareTo(other.isSetLastLoginTimeEnd());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLastLoginTimeEnd()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.lastLoginTimeEnd, other.lastLoginTimeEnd);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetBirthdayStart()).compareTo(other.isSetBirthdayStart());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBirthdayStart()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.birthdayStart, other.birthdayStart);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetBirthdayEnd()).compareTo(other.isSetBirthdayEnd());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBirthdayEnd()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.birthdayEnd, other.birthdayEnd);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUserIdSet()).compareTo(other.isSetUserIdSet());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUserIdSet()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.userIdSet, other.userIdSet);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLocationIdSet()).compareTo(other.isSetLocationIdSet());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLocationIdSet()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.locationIdSet, other.locationIdSet);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("UserLocationBo(");
    boolean first = true;

    sb.append("id:");
    sb.append(this.id);
    first = false;
    if (!first) sb.append(", ");
    sb.append("userId:");
    sb.append(this.userId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("locationId:");
    sb.append(this.locationId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("lastModifyTime:");
    sb.append(this.lastModifyTime);
    first = false;
    if (!first) sb.append(", ");
    sb.append("idSet:");
    if (this.idSet == null) {
      sb.append("null");
    } else {
      sb.append(this.idSet);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("lastModifyTimeStart:");
    sb.append(this.lastModifyTimeStart);
    first = false;
    if (!first) sb.append(", ");
    sb.append("lastModifyTimeEnd:");
    sb.append(this.lastModifyTimeEnd);
    first = false;
    if (!first) sb.append(", ");
    sb.append("createTimeStart:");
    sb.append(this.createTimeStart);
    first = false;
    if (!first) sb.append(", ");
    sb.append("createTimeEnd:");
    sb.append(this.createTimeEnd);
    first = false;
    if (!first) sb.append(", ");
    sb.append("lastLoginTimeStart:");
    sb.append(this.lastLoginTimeStart);
    first = false;
    if (!first) sb.append(", ");
    sb.append("lastLoginTimeEnd:");
    sb.append(this.lastLoginTimeEnd);
    first = false;
    if (!first) sb.append(", ");
    sb.append("birthdayStart:");
    sb.append(this.birthdayStart);
    first = false;
    if (!first) sb.append(", ");
    sb.append("birthdayEnd:");
    sb.append(this.birthdayEnd);
    first = false;
    if (!first) sb.append(", ");
    sb.append("userIdSet:");
    if (this.userIdSet == null) {
      sb.append("null");
    } else {
      sb.append(this.userIdSet);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("locationIdSet:");
    if (this.locationIdSet == null) {
      sb.append("null");
    } else {
      sb.append(this.locationIdSet);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class UserLocationBoStandardSchemeFactory implements SchemeFactory {
    public UserLocationBoStandardScheme getScheme() {
      return new UserLocationBoStandardScheme();
    }
  }

  private static class UserLocationBoStandardScheme extends StandardScheme<UserLocationBo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, UserLocationBo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.id = iprot.readI32();
              struct.setIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // USER_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.userId = iprot.readI32();
              struct.setUserIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // LOCATION_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.locationId = iprot.readI32();
              struct.setLocationIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // LAST_MODIFY_TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.lastModifyTime = iprot.readI64();
              struct.setLastModifyTimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // ID_SET
            if (schemeField.type == org.apache.thrift.protocol.TType.SET) {
              {
                org.apache.thrift.protocol.TSet _set0 = iprot.readSetBegin();
                struct.idSet = new HashSet<Integer>(2*_set0.size);
                for (int _i1 = 0; _i1 < _set0.size; ++_i1)
                {
                  int _elem2;
                  _elem2 = iprot.readI32();
                  struct.idSet.add(_elem2);
                }
                iprot.readSetEnd();
              }
              struct.setIdSetIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // LAST_MODIFY_TIME_START
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.lastModifyTimeStart = iprot.readI64();
              struct.setLastModifyTimeStartIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // LAST_MODIFY_TIME_END
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.lastModifyTimeEnd = iprot.readI64();
              struct.setLastModifyTimeEndIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // CREATE_TIME_START
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.createTimeStart = iprot.readI64();
              struct.setCreateTimeStartIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // CREATE_TIME_END
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.createTimeEnd = iprot.readI64();
              struct.setCreateTimeEndIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // LAST_LOGIN_TIME_START
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.lastLoginTimeStart = iprot.readI64();
              struct.setLastLoginTimeStartIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 11: // LAST_LOGIN_TIME_END
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.lastLoginTimeEnd = iprot.readI64();
              struct.setLastLoginTimeEndIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 12: // BIRTHDAY_START
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.birthdayStart = iprot.readI64();
              struct.setBirthdayStartIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 13: // BIRTHDAY_END
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.birthdayEnd = iprot.readI64();
              struct.setBirthdayEndIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 14: // USER_ID_SET
            if (schemeField.type == org.apache.thrift.protocol.TType.SET) {
              {
                org.apache.thrift.protocol.TSet _set3 = iprot.readSetBegin();
                struct.userIdSet = new HashSet<Integer>(2*_set3.size);
                for (int _i4 = 0; _i4 < _set3.size; ++_i4)
                {
                  int _elem5;
                  _elem5 = iprot.readI32();
                  struct.userIdSet.add(_elem5);
                }
                iprot.readSetEnd();
              }
              struct.setUserIdSetIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 15: // LOCATION_ID_SET
            if (schemeField.type == org.apache.thrift.protocol.TType.SET) {
              {
                org.apache.thrift.protocol.TSet _set6 = iprot.readSetBegin();
                struct.locationIdSet = new HashSet<Integer>(2*_set6.size);
                for (int _i7 = 0; _i7 < _set6.size; ++_i7)
                {
                  int _elem8;
                  _elem8 = iprot.readI32();
                  struct.locationIdSet.add(_elem8);
                }
                iprot.readSetEnd();
              }
              struct.setLocationIdSetIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, UserLocationBo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(ID_FIELD_DESC);
      oprot.writeI32(struct.id);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(USER_ID_FIELD_DESC);
      oprot.writeI32(struct.userId);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(LOCATION_ID_FIELD_DESC);
      oprot.writeI32(struct.locationId);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(LAST_MODIFY_TIME_FIELD_DESC);
      oprot.writeI64(struct.lastModifyTime);
      oprot.writeFieldEnd();
      if (struct.idSet != null) {
        oprot.writeFieldBegin(ID_SET_FIELD_DESC);
        {
          oprot.writeSetBegin(new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.I32, struct.idSet.size()));
          for (int _iter9 : struct.idSet)
          {
            oprot.writeI32(_iter9);
          }
          oprot.writeSetEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(LAST_MODIFY_TIME_START_FIELD_DESC);
      oprot.writeI64(struct.lastModifyTimeStart);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(LAST_MODIFY_TIME_END_FIELD_DESC);
      oprot.writeI64(struct.lastModifyTimeEnd);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(CREATE_TIME_START_FIELD_DESC);
      oprot.writeI64(struct.createTimeStart);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(CREATE_TIME_END_FIELD_DESC);
      oprot.writeI64(struct.createTimeEnd);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(LAST_LOGIN_TIME_START_FIELD_DESC);
      oprot.writeI64(struct.lastLoginTimeStart);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(LAST_LOGIN_TIME_END_FIELD_DESC);
      oprot.writeI64(struct.lastLoginTimeEnd);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(BIRTHDAY_START_FIELD_DESC);
      oprot.writeI64(struct.birthdayStart);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(BIRTHDAY_END_FIELD_DESC);
      oprot.writeI64(struct.birthdayEnd);
      oprot.writeFieldEnd();
      if (struct.userIdSet != null) {
        oprot.writeFieldBegin(USER_ID_SET_FIELD_DESC);
        {
          oprot.writeSetBegin(new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.I32, struct.userIdSet.size()));
          for (int _iter10 : struct.userIdSet)
          {
            oprot.writeI32(_iter10);
          }
          oprot.writeSetEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.locationIdSet != null) {
        oprot.writeFieldBegin(LOCATION_ID_SET_FIELD_DESC);
        {
          oprot.writeSetBegin(new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.I32, struct.locationIdSet.size()));
          for (int _iter11 : struct.locationIdSet)
          {
            oprot.writeI32(_iter11);
          }
          oprot.writeSetEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class UserLocationBoTupleSchemeFactory implements SchemeFactory {
    public UserLocationBoTupleScheme getScheme() {
      return new UserLocationBoTupleScheme();
    }
  }

  private static class UserLocationBoTupleScheme extends TupleScheme<UserLocationBo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, UserLocationBo struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetId()) {
        optionals.set(0);
      }
      if (struct.isSetUserId()) {
        optionals.set(1);
      }
      if (struct.isSetLocationId()) {
        optionals.set(2);
      }
      if (struct.isSetLastModifyTime()) {
        optionals.set(3);
      }
      if (struct.isSetIdSet()) {
        optionals.set(4);
      }
      if (struct.isSetLastModifyTimeStart()) {
        optionals.set(5);
      }
      if (struct.isSetLastModifyTimeEnd()) {
        optionals.set(6);
      }
      if (struct.isSetCreateTimeStart()) {
        optionals.set(7);
      }
      if (struct.isSetCreateTimeEnd()) {
        optionals.set(8);
      }
      if (struct.isSetLastLoginTimeStart()) {
        optionals.set(9);
      }
      if (struct.isSetLastLoginTimeEnd()) {
        optionals.set(10);
      }
      if (struct.isSetBirthdayStart()) {
        optionals.set(11);
      }
      if (struct.isSetBirthdayEnd()) {
        optionals.set(12);
      }
      if (struct.isSetUserIdSet()) {
        optionals.set(13);
      }
      if (struct.isSetLocationIdSet()) {
        optionals.set(14);
      }
      oprot.writeBitSet(optionals, 15);
      if (struct.isSetId()) {
        oprot.writeI32(struct.id);
      }
      if (struct.isSetUserId()) {
        oprot.writeI32(struct.userId);
      }
      if (struct.isSetLocationId()) {
        oprot.writeI32(struct.locationId);
      }
      if (struct.isSetLastModifyTime()) {
        oprot.writeI64(struct.lastModifyTime);
      }
      if (struct.isSetIdSet()) {
        {
          oprot.writeI32(struct.idSet.size());
          for (int _iter12 : struct.idSet)
          {
            oprot.writeI32(_iter12);
          }
        }
      }
      if (struct.isSetLastModifyTimeStart()) {
        oprot.writeI64(struct.lastModifyTimeStart);
      }
      if (struct.isSetLastModifyTimeEnd()) {
        oprot.writeI64(struct.lastModifyTimeEnd);
      }
      if (struct.isSetCreateTimeStart()) {
        oprot.writeI64(struct.createTimeStart);
      }
      if (struct.isSetCreateTimeEnd()) {
        oprot.writeI64(struct.createTimeEnd);
      }
      if (struct.isSetLastLoginTimeStart()) {
        oprot.writeI64(struct.lastLoginTimeStart);
      }
      if (struct.isSetLastLoginTimeEnd()) {
        oprot.writeI64(struct.lastLoginTimeEnd);
      }
      if (struct.isSetBirthdayStart()) {
        oprot.writeI64(struct.birthdayStart);
      }
      if (struct.isSetBirthdayEnd()) {
        oprot.writeI64(struct.birthdayEnd);
      }
      if (struct.isSetUserIdSet()) {
        {
          oprot.writeI32(struct.userIdSet.size());
          for (int _iter13 : struct.userIdSet)
          {
            oprot.writeI32(_iter13);
          }
        }
      }
      if (struct.isSetLocationIdSet()) {
        {
          oprot.writeI32(struct.locationIdSet.size());
          for (int _iter14 : struct.locationIdSet)
          {
            oprot.writeI32(_iter14);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, UserLocationBo struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(15);
      if (incoming.get(0)) {
        struct.id = iprot.readI32();
        struct.setIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.userId = iprot.readI32();
        struct.setUserIdIsSet(true);
      }
      if (incoming.get(2)) {
        struct.locationId = iprot.readI32();
        struct.setLocationIdIsSet(true);
      }
      if (incoming.get(3)) {
        struct.lastModifyTime = iprot.readI64();
        struct.setLastModifyTimeIsSet(true);
      }
      if (incoming.get(4)) {
        {
          org.apache.thrift.protocol.TSet _set15 = new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.I32, iprot.readI32());
          struct.idSet = new HashSet<Integer>(2*_set15.size);
          for (int _i16 = 0; _i16 < _set15.size; ++_i16)
          {
            int _elem17;
            _elem17 = iprot.readI32();
            struct.idSet.add(_elem17);
          }
        }
        struct.setIdSetIsSet(true);
      }
      if (incoming.get(5)) {
        struct.lastModifyTimeStart = iprot.readI64();
        struct.setLastModifyTimeStartIsSet(true);
      }
      if (incoming.get(6)) {
        struct.lastModifyTimeEnd = iprot.readI64();
        struct.setLastModifyTimeEndIsSet(true);
      }
      if (incoming.get(7)) {
        struct.createTimeStart = iprot.readI64();
        struct.setCreateTimeStartIsSet(true);
      }
      if (incoming.get(8)) {
        struct.createTimeEnd = iprot.readI64();
        struct.setCreateTimeEndIsSet(true);
      }
      if (incoming.get(9)) {
        struct.lastLoginTimeStart = iprot.readI64();
        struct.setLastLoginTimeStartIsSet(true);
      }
      if (incoming.get(10)) {
        struct.lastLoginTimeEnd = iprot.readI64();
        struct.setLastLoginTimeEndIsSet(true);
      }
      if (incoming.get(11)) {
        struct.birthdayStart = iprot.readI64();
        struct.setBirthdayStartIsSet(true);
      }
      if (incoming.get(12)) {
        struct.birthdayEnd = iprot.readI64();
        struct.setBirthdayEndIsSet(true);
      }
      if (incoming.get(13)) {
        {
          org.apache.thrift.protocol.TSet _set18 = new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.I32, iprot.readI32());
          struct.userIdSet = new HashSet<Integer>(2*_set18.size);
          for (int _i19 = 0; _i19 < _set18.size; ++_i19)
          {
            int _elem20;
            _elem20 = iprot.readI32();
            struct.userIdSet.add(_elem20);
          }
        }
        struct.setUserIdSetIsSet(true);
      }
      if (incoming.get(14)) {
        {
          org.apache.thrift.protocol.TSet _set21 = new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.I32, iprot.readI32());
          struct.locationIdSet = new HashSet<Integer>(2*_set21.size);
          for (int _i22 = 0; _i22 < _set21.size; ++_i22)
          {
            int _elem23;
            _elem23 = iprot.readI32();
            struct.locationIdSet.add(_elem23);
          }
        }
        struct.setLocationIdSetIsSet(true);
      }
    }
  }

}

